import type { WorkshopSection } from "@/lib/workshop/types";

export const DEEP_SECTIONS_PART2: Record<string, WorkshopSection[]> = {
  "multimodal-fundamentals": [
    {
      id: "when",
      num: "01",
      navLabel: "When vision",
      eyebrow: "Part 1 · Step 01",
      title: "Text vs image input",
      lab: {
        kind: "compare",
        question: "User uploads network diagram screenshot for 'which subnet is payments-api?'",
        left: { title: "Text-only model", body: "OCR pipeline → text → RAG; layout and arrows may be lost." },
        right: { title: "Vision-capable model", body: "Can read diagram directly; still needs ACL on stored images." },
        pick: [{ id: "left", label: "OCR + RAG" }, { id: "right", label: "Native vision" }],
        correctId: "right",
        ok: "Topology questions often need spatial structure — vision or high-quality diagram parsing.",
        bad: "Plain text chunking of diagrams loses relationships.",
      },
    },
    {
      id: "risk",
      num: "02",
      navLabel: "Risks",
      eyebrow: "Part 2 · Step 02",
      title: "Sensitive screenshots",
      lab: {
        kind: "checklist",
        intro: "Allowing screenshot upload in copilot:",
        items: [
          { id: "1", label: "DLP scan on upload" },
          { id: "2", label: "Retention policy for image blobs" },
          { id: "3", label: "Redact customer data in thumbnails" },
          { id: "4", label: "Eval set includes diagram-heavy questions" },
        ],
        goodScore: 4,
        goodMsg: "Multimodal expands attack and privacy surface — treat like production data.",
        badMsg: "Screenshots may contain PII and credentials.",
      },
    },
  ],
  "embedding-model-choice": [
    {
      id: "dims",
      num: "01",
      navLabel: "Dimensions",
      eyebrow: "Part 1 · Step 01",
      title: "768 vs 3072",
      lab: {
        kind: "profiles",
        profiles: [
          {
            id: "small",
            label: "768-dim model",
            body: "Faster index, less RAM; may confuse similar runbook titles.",
            verdict: "Good for under 200k chunks with strong metadata filters.",
          },
          {
            id: "large",
            label: "3072-dim model",
            body: "Better semantic separation for paraphrased incident symptoms.",
            verdict: "Reindex cost hurts — version embeddings in metadata.",
          },
        ],
      },
    },
    {
      id: "reindex",
      num: "02",
      navLabel: "Reindex",
      eyebrow: "Part 2 · Step 02",
      title: "Migration quiz",
      lab: {
        kind: "quiz",
        prompt: "You switch embed models. Required step before cutover?",
        options: [
          { id: "a", label: "Dual-write both indexes + compare recall@10 on golden set" },
          { id: "b", label: "Delete old index immediately" },
          { id: "c", label: "Only update README" },
        ],
        correctId: "a",
        ok: "Embedding space is not compatible across models — reindex and eval.",
        bad: "Mixed vectors in one index break search geometry.",
      },
    },
  ],
  "loss-and-objectives": [
    {
      id: "clm",
      num: "01",
      navLabel: "CLM",
      eyebrow: "Part 1 · Step 01",
      title: "Next-token pressure",
      prose: "Causal LM loss rewards plausible continuation — not factual verification.",
      lab: {
        kind: "steps",
        steps: [
          { id: "s1", label: "Prompt", body: "Complete: 'The SLA for P1 is'" },
          { id: "s2", label: "Behavior", body: "Model invents a number if policy not in context." },
          { id: "s3", label: "Mitigation", body: "RAG + citation requirement + eval on policy ids." },
        ],
      },
    },
    {
      id: "match",
      num: "02",
      navLabel: "Match",
      eyebrow: "Part 2 · Step 02",
      title: "Objective → failure",
      lab: {
        kind: "quiz",
        prompt: "Model trained only to minimize perplexity on forums. Risk for enterprise copilot?",
        options: [
          { id: "a", label: "Overconfident casual tone on compliance questions" },
          { id: "b", label: "Cannot count tokens" },
          { id: "c", label: "Attention stops working" },
        ],
        correctId: "a",
        ok: "Training objective shapes style and calibration — add SFT/RLHF and grounding for enterprise.",
        bad: "Perplexity does not encode legal accuracy.",
      },
    },
  ],
  "query-rewriting": [
    {
      id: "concept",
      num: "01",
      navLabel: "Strategies",
      eyebrow: "Part 1 · Step 01",
      title: "Three rewrite moves",
      prose: "Lexical fixes help INC IDs; semantic expansion helps symptoms; decomposition helps multi-part questions.",
      lab: {
        kind: "profiles",
        prompt: 'User query: "payments broken yesterday who fixes"',
        profiles: [
          {
            id: "expand",
            label: "Expand",
            body: "payments-api outage 2024-09-30 on-call escalation Team Payments",
            verdict: "Good when user omits service names — watch ACL scope.",
          },
          {
            id: "decompose",
            label: "Decompose",
            body: "(1) payments-api timeline (2) ownership / escalation path",
            verdict: "Run retrieval per sub-query for multi-hop IT questions.",
          },
          {
            id: "none",
            label: "No rewrite",
            body: "Literal embedding of messy phrase.",
            verdict: "Keep for power users with exact error codes.",
          },
        ],
      },
    },
    {
      id: "lab2",
      num: "02",
      navLabel: "Quiz",
      eyebrow: "Part 2 · Step 02",
      title: "INC id case",
      lab: {
        kind: "quiz",
        prompt: 'Query: "INC-1042" — what rewrite do you apply?',
        options: [
          { id: "a", label: "None — hybrid search handles IDs" },
          { id: "b", label: "Expand into fictional narrative" },
          { id: "c", label: "Translate to another language" },
        ],
        correctId: "a",
        ok: "Exact ticket IDs should hit BM25/hybrid — avoid hallucinated expansions.",
        bad: "Rewriting can erase the strongest lexical signal.",
      },
    },
  ],
  "hyde-multi-query": [
    {
      id: "hyde",
      num: "01",
      navLabel: "HyDE",
      eyebrow: "Part 1 · Step 01",
      title: "Hypothetical document",
      lab: {
        kind: "profiles",
        prompt: 'User: "vpn keeps dropping for payments team"',
        profiles: [
          {
            id: "on",
            label: "HyDE on",
            body: "LLM writes fake runbook paragraph → embed paragraph → retrieve.",
            verdict: "Can help vague queries; fake doc may retrieve wrong tenant's VPN doc.",
          },
          {
            id: "off",
            label: "HyDE off",
            body: "Embed user query directly.",
            verdict: "Safer when queries already contain service names and error codes.",
          },
        ],
      },
    },
    {
      id: "multi",
      num: "02",
      navLabel: "Multi-query",
      eyebrow: "Part 2 · Step 02",
      title: "Fusion",
      lab: {
        kind: "quiz",
        prompt: "You generate 3 query variants and get disjoint top-k lists. Merge how?",
        options: [
          { id: "a", label: "RRF or union dedupe by chunk id" },
          { id: "b", label: "Average the embedding vectors of queries" },
          { id: "c", label: "Pick random variant" },
        ],
        correctId: "a",
        ok: "Standard production pattern — same as hybrid fusion intuition.",
        bad: "Averaging queries is not equivalent to multi-list fusion.",
      },
    },
  ],
  "semantic-cache": [
    {
      id: "hit",
      num: "01",
      navLabel: "Hits",
      eyebrow: "Part 1 · Step 01",
      title: "Paraphrase hits",
      lab: {
        kind: "profiles",
        profiles: [
          {
            id: "hit",
            label: "Cache hit",
            body: '"reset vpn token" ≈ "how do I refresh vpn creds" above 0.92 similarity.',
            verdict: "Return cached answer + log hit; watch ACL — same intent, different users?",
          },
          {
            id: "miss",
            label: "Cache miss",
            body: '"INC-1042 timeline" vs "INC-1043 timeline" — similar embedding, different facts.',
            verdict: "Do not cache solely on embedding — include tenant + entity keys.",
          },
        ],
      },
    },
    {
      id: "thresh",
      num: "02",
      navLabel: "Threshold",
      eyebrow: "Part 2 · Step 02",
      title: "Tune similarity",
      lab: {
        kind: "slider",
        label: "Similarity threshold (0.85–0.98)",
        min: 85,
        max: 98,
        step: 1,
        thresholds: [
          { max: 89, msg: "Too many false hits — wrong policy answers reused.", warn: true },
          { max: 94, msg: "Sweet spot for many IT FAQs — validate on eval paraphrases." },
          { max: 98, msg: "Almost exact match only — little cache benefit.", warn: true },
        ],
      },
    },
  ],
  "multi-tenant-rag": [
    {
      id: "filter",
      num: "01",
      navLabel: "Filters",
      eyebrow: "Part 1 · Step 01",
      title: "Tenant isolation",
      lab: {
        kind: "quiz",
        prompt: "Shared vector index for payments + corp tenants. Minimum control?",
        options: [
          { id: "a", label: "Mandatory metadata filter on tenant_id at query time" },
          { id: "b", label: "Trust the LLM not to leak" },
          { id: "c", label: "Separate models per tenant only" },
        ],
        correctId: "a",
        ok: "Enforce at retrieval — generation cannot unsee a leaked chunk.",
        bad: "Prompt pleading is not ACL.",
      },
    },
    {
      id: "test",
      num: "02",
      navLabel: "Test",
      eyebrow: "Part 2 · Step 02",
      title: "Cross-tenant tests",
      lab: {
        kind: "checklist",
        intro: "Before GA for multi-tenant copilot:",
        items: [
          { id: "1", label: "Automated tests query other tenant's INC ids" },
          { id: "2", label: "Logs include tenant_id on retrieval spans" },
          { id: "3", label: "Index rebuild preserves metadata schema" },
          { id: "4", label: "Red team attempts injection via shared corpus" },
        ],
        goodScore: 4,
        goodMsg: "Treat tenant bleed as Sev-1 security defect.",
        badMsg: "One missing filter exposes competitor data in shared SaaS stacks.",
      },
    },
  ],
  "rag-citations": [
    {
      id: "ui",
      num: "01",
      navLabel: "UI",
      eyebrow: "Part 1 · Step 01",
      title: "Trust design",
      lab: {
        kind: "compare",
        question: "User sees answer with footnote [3] but chunk is wrong policy version.",
        left: { title: "Highlight + open chunk", body: "User verifies text in side panel — catches mismatch." },
        right: { title: "Footnote only", body: "Number looks authoritative; users do not click." },
        pick: [{ id: "left", label: "Inspectable cite" }, { id: "right", label: "Opaque footnote" }],
        correctId: "left",
        ok: "Citations are UX for verification — pin chunk text inline.",
        bad: "Decorative citations increase false trust.",
      },
    },
    {
      id: "wrong",
      num: "02",
      navLabel: "Detect",
      eyebrow: "Part 2 · Step 02",
      title: "Wrong attribution",
      lab: {
        kind: "quiz",
        prompt: "Answer cites chunk A but prose mentions facts only in chunk B. Detect how?",
        options: [
          { id: "a", label: "NLI / entailment check answer ⊆ union(cited chunks)" },
          { id: "b", label: "Raise temperature" },
          { id: "c", label: "Remove citations" },
        ],
        correctId: "a",
        ok: "Automated grounding checks in CI eval — flag before ship.",
        bad: "Hiding citations removes the only user defense.",
      },
    },
  ],
  "conversational-rag": [
    {
      id: "refresh",
      num: "01",
      navLabel: "Refresh",
      eyebrow: "Part 1 · Step 01",
      title: "When to re-retrieve",
      lab: {
        kind: "profiles",
        prompt: "Multi-turn chat about INC-1042",
        profiles: [
          {
            id: "follow",
            label: 'Follow-up: "who is on-call now?"',
            body: "New retrieval — roster changes; do not reuse first turn chunks only.",
            verdict: "Schedule re-retrieve on entity/time-sensitive intents.",
          },
          {
            id: "clarify",
            label: 'Follow-up: "explain that in simpler words"',
            body: "Same chunks OK if prior answer was grounded.",
            verdict: "Rephrase without new search when context still valid.",
          },
        ],
      },
    },
    {
      id: "history",
      num: "02",
      navLabel: "History",
      eyebrow: "Part 2 · Step 02",
      title: "Context budget",
      lab: {
        kind: "quiz",
        prompt: "Thread has 40 turns. Retrieval query should use?",
        options: [
          { id: "a", label: "Latest user message + compressed summary of thread" },
          { id: "b", label: "Full raw thread as query string" },
          { id: "c", label: "First message only" },
        ],
        correctId: "a",
        ok: "Query formation is its own engineering problem in conversational RAG.",
        bad: "Full thread dilutes embedding signal.",
      },
    },
  ],
  "structured-rag": [
    {
      id: "openapi",
      num: "01",
      navLabel: "OpenAPI",
      eyebrow: "Part 1 · Step 01",
      title: "Schema chunks",
      lab: {
        kind: "steps",
        steps: [
          { id: "s1", label: "Ingest", body: "Chunk OpenAPI paths with method + parameters per chunk." },
          { id: "s2", label: "Retrieve", body: 'User: "POST /incidents body fields?" → hits path chunk.' },
          { id: "s3", label: "Generate", body: "Model lists required fields grounded in schema chunk." },
        ],
      },
    },
    {
      id: "mix",
      num: "02",
      navLabel: "Mix",
      eyebrow: "Part 2 · Step 02",
      title: "Prose + JSON",
      lab: {
        kind: "quiz",
        prompt: "Internal API docs + narrative runbooks. Index strategy?",
        options: [
          { id: "a", label: "Same index with content_type metadata + filters when needed" },
          { id: "b", label: "Dump all JSON into one giant text blob" },
          { id: "c", label: "Only index prose" },
        ],
        correctId: "a",
        ok: "Structured RAG needs typed metadata for hybrid developer questions.",
        bad: "Minified JSON blobs embed poorly.",
      },
    },
  ],
};
