import type { WorkshopSection } from "@/lib/workshop/types";

export const DEEP_SECTIONS_PART3: Record<string, WorkshopSection[]> = {
  "code-rag": [
    {
      id: "chunk",
      num: "01",
      navLabel: "Chunking",
      eyebrow: "Part 1 · Step 01",
      title: "AST vs lines",
      lab: {
        kind: "compare",
        question: "Index internal Go SDK for copilot code answers.",
        left: { title: "Fixed 80-line windows", body: "Splits functions; imports orphaned from body." },
        right: { title: "AST / symbol chunks", body: "One chunk per exported func with package header context." },
        pick: [{ id: "left", label: "Line chunks" }, { id: "right", label: "Symbol chunks" }],
        correctId: "right",
        ok: "Code RAG needs symbol boundaries — pair with graph of imports optional.",
        bad: "Line splits break compile-ready answers.",
      },
    },
    {
      id: "acl",
      num: "02",
      navLabel: "ACL",
      eyebrow: "Part 2 · Step 02",
      title: "Repo access",
      lab: {
        kind: "checklist",
        intro: "Code search copilot:",
        items: [
          { id: "1", label: "Index only repos user can clone" },
          { id: "2", label: "Strip secrets via scanner in CI before embed" },
          { id: "3", label: "Block retrieval from archived vuln branches" },
        ],
        goodScore: 3,
        goodMsg: "Code indices are credential and IP sensitive.",
        badMsg: "Leaked API keys in embeddings are painful to rotate.",
      },
    },
  ],
  "retrieval-metrics-lab": [
    {
      id: "recall",
      num: "01",
      navLabel: "Recall@k",
      eyebrow: "Part 1 · Step 01",
      title: "Did the right chunk appear?",
      lab: {
        kind: "slider",
        label: "k in recall@k (1–20)",
        min: 1,
        max: 20,
        step: 1,
        thresholds: [
          { max: 3, msg: "Strict — good for reranker input size; may miss recall on hard queries.", warn: true },
          { max: 10, msg: "Common pre-rerank window — tune with golden INC queries." },
          { max: 20, msg: "Loose — high recall but noisy for cross-encoder cost." },
        ],
      },
    },
    {
      id: "ndcg",
      num: "02",
      navLabel: "nDCG",
      eyebrow: "Part 2 · Step 02",
      title: "Rank quality",
      lab: {
        kind: "quiz",
        prompt: "Right chunk at position 8 of 10. Metric most sensitive to that bad rank?",
        options: [
          { id: "a", label: "nDCG / MRR" },
          { id: "b", label: "Exact match accuracy on generation" },
          { id: "c", label: "Token perplexity" },
        ],
        correctId: "a",
        ok: "Retrieval metrics punish late hits — reranking exists to fix this.",
        bad: "Generation metrics hide retrieval ordering problems.",
      },
    },
  ],
  "golden-set-design": [
    {
      id: "coverage",
      num: "01",
      navLabel: "Coverage",
      eyebrow: "Part 1 · Step 01",
      title: "Intent map",
      lab: {
        kind: "checklist",
        intro: "Golden set for internal search:",
        items: [
          { id: "1", label: "INC id lookup" },
          { id: "2", label: "Paraphrased symptom" },
          { id: "3", label: "Policy number question" },
          { id: "4", label: "Adversarial injection in corpus" },
          { id: "5", label: "Cross-tenant negative test" },
        ],
        goodScore: 5,
        goodMsg: "Coverage beats sheer count — 40 diverse beats 400 duplicates.",
        badMsg: "Missing injection/tenant cases miss real regressions.",
      },
    },
    {
      id: "maint",
      num: "02",
      navLabel: "Maintain",
      eyebrow: "Part 2 · Step 02",
      title: "Living set",
      lab: {
        kind: "quiz",
        prompt: "Production wrong answer screenshot arrives. First golden set action?",
        options: [
          { id: "a", label: "Add failing query + expected chunk ids; block release until pass" },
          { id: "b", label: "Delete evals to unblock deploy" },
          { id: "c", label: "Raise temperature" },
        ],
        correctId: "a",
        ok: "Golden sets grow from incidents — like postmortem action items.",
        bad: "Deleting evals guarantees repeat.",
      },
    },
  ],
  "llm-as-judge": [
    {
      id: "bias",
      num: "01",
      navLabel: "Bias",
      eyebrow: "Part 1 · Step 01",
      title: "Judge pitfalls",
      lab: {
        kind: "profiles",
        profiles: [
          {
            id: "verbose",
            label: "Verbose wins",
            body: "Judge model scores longer answer higher though both wrong on policy.",
            verdict: "Use rubric + length-normalization; spot-check with humans.",
          },
          {
            id: "self",
            label: "Same family judge",
            body: "GPT judges GPT — prefers familiar phrasing.",
            verdict: "Cross-model judges + golden human labels on sample.",
          },
        ],
      },
    },
    {
      id: "rubric",
      num: "02",
      navLabel: "Rubric",
      eyebrow: "Part 2 · Step 02",
      title: "Structured judge",
      lab: {
        kind: "quiz",
        prompt: "Best judge prompt shape for runbook Q&A?",
        options: [
          { id: "a", label: "Score 1-5 on groundedness, cite violating sentence" },
          { id: "b", label: "Thumbs up/down only" },
          { id: "c", label: "Ask judge to rewrite answer" },
        ],
        correctId: "a",
        ok: "Rubrics make judges debuggable in CI logs.",
        bad: "Binary judge hides why regression happened.",
      },
    },
  ],
  "synthetic-eval-data": [
    {
      id: "gen",
      num: "01",
      navLabel: "Generate",
      eyebrow: "Part 1 · Step 01",
      title: "Synthetic Q/A",
      lab: {
        kind: "steps",
        steps: [
          { id: "s1", label: "Generate", body: "LLM writes Q/A from runbook chunks." },
          { id: "s2", label: "Filter", body: "Drop pairs where answer not entailed by chunk." },
          { id: "s3", label: "Human", body: "Sample 5% for review before merging into golden set." },
        ],
      },
    },
    {
      id: "poison",
      num: "02",
      navLabel: "Poison",
      eyebrow: "Part 2 · Step 02",
      title: "When synthetic hurts",
      lab: {
        kind: "quiz",
        prompt: "Synthetic data duplicates vendor marketing PDF in index. Risk?",
        options: [
          { id: "a", label: "Eval scores inflate; model looks good on fake easy questions" },
          { id: "b", label: "Faster GPUs" },
          { id: "c", label: "Better BM25" },
        ],
        correctId: "a",
        ok: "Synthetic evals must mirror real query distribution — not easier.",
        bad: "Garbage synthetic sets optimize the wrong thing.",
      },
    },
  ],
  "text-to-sql": [
    {
      id: "sql",
      num: "01",
      navLabel: "SQL",
      eyebrow: "Part 1 · Step 01",
      title: "Approve generated SQL",
      lab: {
        kind: "quiz",
        prompt: 'User: "count open incidents" — model emits: DELETE FROM incidents; --',
        options: [
          { id: "a", label: "Reject — read-only role + allowlist SELECT templates" },
          { id: "b", label: "Run on production warehouse" },
          { id: "c", label: "Ask user to paste password" },
        ],
        correctId: "a",
        ok: "Text-to-SQL needs guardrails: RO user, table allowlist, row limits.",
        bad: "Agents with write SQL are incidents waiting to happen.",
      },
    },
    {
      id: "schema",
      num: "02",
      navLabel: "Schema",
      eyebrow: "Part 2 · Step 02",
      title: "Ground schema",
      lab: {
        kind: "checklist",
        intro: "CMDB analytics copilot:",
        items: [
          { id: "1", label: "Inject relevant table DDL into context, not whole warehouse" },
          { id: "2", label: "LIMIT enforced server-side" },
          { id: "3", label: "Log SQL + user for audit" },
        ],
        goodScore: 3,
        goodMsg: "Schema grounding reduces wrong joins across service vs incident tables.",
        badMsg: "Whole-schema dump blows context and confuses model.",
      },
    },
  ],
  "multimodal-rag": [
    {
      id: "fuse",
      num: "01",
      navLabel: "Fuse",
      eyebrow: "Part 1 · Step 01",
      title: "Image + text chunks",
      lab: {
        kind: "compare",
        question: "Runbook has architecture PNG + steps in prose.",
        left: { title: "OCR only", body: "Text index only; arrow topology weak." },
        right: { title: "Image embed + text embed", body: "Retrieve both modalities; fuse in prompt with labels." },
        pick: [{ id: "left", label: "OCR path" }, { id: "right", label: "Dual index" }],
        correctId: "right",
        ok: "Multimodal RAG = multiple indexes or unified multimodal embedder — eval both.",
        bad: "OCR-only loses layout for failover diagrams.",
      },
    },
    {
      id: "eval",
      num: "02",
      navLabel: "Eval",
      eyebrow: "Part 2 · Step 02",
      title: "Diagram questions",
      lab: {
        kind: "quiz",
        prompt: "Golden set for multimodal RAG must include?",
        options: [
          { id: "a", label: "Questions answerable only from diagram chunks" },
          { id: "b", label: "Only text FAQs" },
          { id: "c", label: "Only logo images" },
        ],
        correctId: "a",
        ok: "Otherwise you never test the reason you added vision.",
        bad: "Text-only evals miss modality regressions.",
      },
    },
  ],
  "agent-memory": [
    {
      id: "types",
      num: "01",
      navLabel: "Types",
      eyebrow: "Part 1 · Step 01",
      title: "Memory layers",
      lab: {
        kind: "steps",
        steps: [
          { id: "w", label: "Working", body: "Current tool results and last retrieval in prompt." },
          { id: "e", label: "Episodic", body: "Session transcript summary stored per user thread." },
          { id: "s", label: "Semantic", body: "Long-term facts in vector DB — 'user prefers metric units'." },
        ],
      },
    },
    {
      id: "evict",
      num: "02",
      navLabel: "Evict",
      eyebrow: "Part 2 · Step 02",
      title: "What not to store",
      lab: {
        kind: "quiz",
        prompt: "Agent wants to remember full credit card from ticket. You?",
        options: [
          { id: "a", label: "Refuse storage; DLP block; episodic memory excludes PCI" },
          { id: "b", label: "Store in semantic memory for convenience" },
          { id: "c", label: "Email it to logs" },
        ],
        correctId: "a",
        ok: "Memory expands breach blast radius — classify before persist.",
        bad: "PCI in long-term agent memory is a compliance failure.",
      },
    },
  ],
  "agent-planning": [
    {
      id: "patterns",
      num: "01",
      navLabel: "Patterns",
      eyebrow: "Part 1 · Step 01",
      title: "Control flows",
      lab: {
        kind: "profiles",
        prompt: "Task: create Jira from INC summary",
        profiles: [
          {
            id: "react",
            label: "ReAct loop",
            body: "Think → call create_ticket → observe → maybe call again.",
            verdict: "Flexible; needs tool guardrails and step limits.",
          },
          {
            id: "workflow",
            label: "Fixed workflow",
            body: "Validate INC → draft fields → human approve → create.",
            verdict: "Better for high-risk actions — see HITL module.",
          },
        ],
      },
    },
    {
      id: "risk",
      num: "02",
      navLabel: "Risk",
      eyebrow: "Part 2 · Step 02",
      title: "Pick pattern",
      lab: {
        kind: "quiz",
        prompt: "Agent can restart production service via API. Pattern?",
        options: [
          { id: "a", label: "Workflow + approval + idempotent tool" },
          { id: "b", label: "Free ReAct until success" },
          { id: "c", label: "No tools" },
        ],
        correctId: "a",
        ok: "Planning choice is safety architecture.",
        bad: "Unbounded ReAct on prod tools is unsafe.",
      },
    },
  ],
  "multi-agent-systems": [
    {
      id: "router",
      num: "01",
      navLabel: "Router",
      eyebrow: "Part 1 · Step 01",
      title: "Triage router",
      lab: {
        kind: "steps",
        steps: [
          { id: "s1", label: "Router", body: "Classify: incident vs HR policy vs code question." },
          { id: "s2", label: "Specialist", body: "HR agent has HR index only; code agent has repo index." },
          { id: "s3", label: "Handoff", body: "Return structured handoff object, not raw chat spam." },
        ],
      },
    },
    {
      id: "loop",
      num: "02",
      navLabel: "Loops",
      eyebrow: "Part 2 · Step 02",
      title: "Stop conditions",
      lab: {
        kind: "checklist",
        intro: "Multi-agent INC triage:",
        items: [
          { id: "1", label: "Max hops between agents (e.g. 3)" },
          { id: "2", label: "Shared trace id across handoffs" },
          { id: "3", label: "Human escalation path when router uncertain" },
        ],
        goodScore: 3,
        goodMsg: "Prevents agent ping-pong billing surprises.",
        badMsg: "Unbounded multi-agent loops burn tokens and time.",
      },
    },
  ],
};
