import type { WorkshopSection } from "@/lib/workshop/types";

export const DEEP_SECTIONS_PART5: Record<string, WorkshopSection[]> = {
  "quantization-inference": [
    {
      id: "bits",
      num: "01",
      navLabel: "Bits",
      eyebrow: "Part 1 · Step 01",
      title: "INT4 vs FP16",
      lab: {
        kind: "profiles",
        profiles: [
          {
            id: "fp16",
            label: "FP16",
            body: "Best quality on nuanced policy summarization; 2× VRAM vs INT8.",
            verdict: "Use when quality SLO is tight and traffic moderate.",
          },
          {
            id: "int4",
            label: "INT4",
            body: "Faster/cheaper; may garble rare incident codes.",
            verdict: "Validate on golden set with exact INC ids and error codes.",
          },
        ],
      },
    },
    {
      id: "eval",
      num: "02",
      navLabel: "Eval",
      eyebrow: "Part 2 · Step 02",
      title: "Before deploy",
      lab: {
        kind: "quiz",
        prompt: "Quantized model ships without re-running evals. Risk?",
        options: [
          { id: "a", label: "Silent quality drop on tool JSON formatting" },
          { id: "b", label: "Faster DNS" },
          { id: "c", label: "Better BM25" },
        ],
        correctId: "a",
        ok: "Quant changes logits — always regression-test task-specific suites.",
        bad: "Benchmark perplexity alone misses JSON/tool failures.",
      },
    },
  ],
  "local-llms": [
    {
      id: "when",
      num: "01",
      navLabel: "When",
      eyebrow: "Part 1 · Step 01",
      title: "Local vs API",
      lab: {
        kind: "compare",
        question: "Air-gapped SOC needs summarization of internal alerts.",
        left: { title: "Local Ollama", body: "No egress; you operate patches and GPU." },
        right: { title: "Cloud API", body: "Blocked by policy — not an option." },
        pick: [{ id: "left", label: "Local" }, { id: "right", label: "Cloud" }],
        correctId: "left",
        ok: "Local LLMs win on data residency and air gap — pay in ops toil.",
        bad: "Policy forbids cloud — architecture must respect it.",
      },
    },
    {
      id: "dev",
      num: "02",
      navLabel: "Dev",
      eyebrow: "Part 2 · Step 02",
      title: "Dev laptop use",
      lab: {
        kind: "quiz",
        prompt: "Developers use local 7B for prompt prototyping. Production should?",
        options: [
          { id: "a", label: "Separate approved prod model + eval parity checks" },
          { id: "b", label: "Assume laptop model equals prod" },
          { id: "c", label: "Skip evals" },
        ],
        correctId: "a",
        ok: "Local dev accelerates iteration — prod path still gated.",
        bad: "Behavior diverges wildly across model sizes.",
      },
    },
  ],
  "inference-serving": [
    {
      id: "queue",
      num: "01",
      navLabel: "Queue",
      eyebrow: "Part 1 · Step 01",
      title: "Concurrency",
      lab: {
        kind: "slider",
        label: "Concurrent chat streams per GPU",
        min: 1,
        max: 32,
        step: 1,
        thresholds: [
          { max: 4, msg: "Low contention — KV cache friendly; higher latency under spike.", warn: false },
          { max: 16, msg: "Watch P95 — batching helps throughput, hurts tail latency." },
          { max: 32, msg: "Risk OOM / thrash — need queue + autoscale.", warn: true },
        ],
      },
    },
    {
      id: "batch",
      num: "02",
      navLabel: "Batch",
      eyebrow: "Part 2 · Step 02",
      title: "Batch vs stream",
      lab: {
        kind: "quiz",
        prompt: "Nightly embed 2M chunks job vs user chat. Serving pattern?",
        options: [
          { id: "a", label: "Batch offline for embed; streaming server for chat" },
          { id: "b", label: "Same streaming endpoint for both" },
          { id: "c", label: "Email files to model" },
        ],
        correctId: "a",
        ok: "Different workloads need different serving topologies.",
        bad: "Chat SLOs break when mixed with bulk jobs without isolation.",
      },
    },
  ],
  "rlhf-alignment": [
    {
      id: "loop",
      num: "01",
      navLabel: "Loop",
      eyebrow: "Part 1 · Step 01",
      title: "Reward model intuition",
      lab: {
        kind: "steps",
        steps: [
          { id: "s1", label: "Sample", body: "Policy generates two answers to incident question." },
          { id: "s2", label: "Judge", body: "Humans/rm score which is safer and more accurate." },
          { id: "s3", label: "Update", body: "Policy nudged toward preferred — can overfit judges." },
        ],
      },
    },
    {
      id: "fail",
      num: "02",
      navLabel: "Failures",
      eyebrow: "Part 2 · Step 02",
      title: "Alignment side effects",
      lab: {
        kind: "quiz",
        prompt: "RLHF makes model refuse more often, hurting internal-only copilot. Fix?",
        options: [
          { id: "a", label: "Domain-specific rm + allow grounded answers on internal data" },
          { id: "b", label: "Remove all refusals globally" },
          { id: "c", label: "Disable security" },
        ],
        correctId: "a",
        ok: "Alignment targets must match product — enterprise ≠ consumer chatbot.",
        bad: "Generic refusal tuning blocks legitimate IT tasks.",
      },
    },
  ],
  "dpo-preferences": [
    {
      id: "pair",
      num: "01",
      navLabel: "Pairs",
      eyebrow: "Part 1 · Step 01",
      title: "Preference data",
      lab: {
        kind: "profiles",
        profiles: [
          {
            id: "a",
            label: "Answer A",
            body: "Cites runbook section with INC timeline — formal tone.",
            verdict: "Preferred for enterprise comms DPO set.",
          },
          {
            id: "b",
            label: "Answer B",
            body: "Fun meme tone — no citations.",
            verdict: "Reject for IT leadership brief channel.",
          },
        ],
      },
    },
    {
      id: "vs",
      num: "02",
      navLabel: "vs RLHF",
      eyebrow: "Part 2 · Step 02",
      title: "When DPO",
      lab: {
        kind: "compare",
        question: "Team has 10k A/B human preferences, no reward model team.",
        left: { title: "DPO", body: "Direct preference optimization on pairs." },
        right: { title: "Full RLHF", body: "Train RM + PPO loop — heavier ops." },
        pick: [{ id: "left", label: "DPO" }, { id: "right", label: "RLHF" }],
        correctId: "left",
        ok: "DPO is popular for tone/format when pairs are clean.",
        bad: "RLHF overhead may not be worth small tone tweak.",
      },
    },
  ],
  "feature-flags-ai": [
    {
      id: "roll",
      num: "01",
      navLabel: "Rollout",
      eyebrow: "Part 1 · Step 01",
      title: "Cohort rollout",
      lab: {
        kind: "steps",
        steps: [
          { id: "s1", label: "5%", body: "New retriever behind flag — watch eval + latency." },
          { id: "s2", label: "25%", body: "Expand if golden set neutral or better." },
          { id: "s3", label: "100%", body: "Remove flag; keep kill switch for model route." },
        ],
      },
    },
    {
      id: "gate",
      num: "02",
      navLabel: "Gate",
      eyebrow: "Part 2 · Step 02",
      title: "Eval gate",
      lab: {
        kind: "quiz",
        prompt: "Flag auto-promotes when deploy succeeds. Missing?",
        options: [
          { id: "a", label: "CI eval job must pass before flag enable" },
          { id: "b", label: "Larger favicon" },
          { id: "c", label: "Higher temperature" },
        ],
        correctId: "a",
        ok: "AI features need release gates like any critical service.",
        bad: "Deploy green does not mean answer quality green.",
      },
    },
  ],
  "ai-product-metrics": [
    {
      id: "funnel",
      num: "01",
      navLabel: "Funnel",
      eyebrow: "Part 1 · Step 01",
      title: "Beyond thumbs",
      lab: {
        kind: "steps",
        steps: [
          { id: "s1", label: "Answer", body: "User received copilot response." },
          { id: "s2", label: "Action", body: "User opened cited runbook or filed INC." },
          { id: "s3", label: "Resolve", body: "Ticket closed without reopen — lagging metric." },
        ],
      },
    },
    {
      id: "bad",
      num: "02",
      navLabel: "Vanity",
      eyebrow: "Part 2 · Step 02",
      title: "Vanity trap",
      lab: {
        kind: "quiz",
        prompt: "DAU up but reopen rate on INC also up. Interpretation?",
        options: [
          { id: "a", label: "Copilot may be confident but wrong — dig into quality metrics" },
          { id: "b", label: "Success — ignore reopen" },
          { id: "c", label: "Disable metrics" },
        ],
        correctId: "a",
        ok: "Product metrics must tie to outcomes, not chat volume.",
        bad: "Engagement without resolution is anti-value.",
      },
    },
  ],
  "enterprise-copilot-patterns": [
    {
      id: "patterns",
      num: "01",
      navLabel: "Patterns",
      eyebrow: "Part 1 · Step 01",
      title: "Search / draft / act",
      lab: {
        kind: "profiles",
        prompt: "IT workflows:",
        profiles: [
          {
            id: "search",
            label: "Search",
            body: "RAG Q&A with citations — read-only, lowest risk.",
            verdict: "Default first ship for internal docs.",
          },
          {
            id: "act",
            label: "Act",
            body: "Agent creates tickets/changes — needs HITL and tool perms.",
            verdict: "Phase 2 after eval + security signoff.",
          },
        ],
      },
    },
    {
      id: "pick",
      num: "02",
      navLabel: "Pick",
      eyebrow: "Part 2 · Step 02",
      title: "Match workflow",
      lab: {
        kind: "quiz",
        prompt: "User needs draft exec email from postmortem — pattern?",
        options: [
          { id: "a", label: "Draft with human send — not autonomous email tool" },
          { id: "b", label: "Autonomous mass email agent" },
          { id: "c", label: "No AI" },
        ],
        correctId: "a",
        ok: "Draft pattern keeps human accountability on external comms.",
        bad: "Autonomous email is high blast radius.",
      },
    },
  ],
  "workflow-automation-ai": [
    {
      id: "bpmn",
      num: "01",
      navLabel: "Fixed steps",
      eyebrow: "Part 1 · Step 01",
      title: "LLM in workflow",
      lab: {
        kind: "steps",
        steps: [
          { id: "s1", label: "Trigger", body: "INC severity=1 opens workflow." },
          { id: "s2", label: "LLM step", body: "Summarize timeline into template fields — schema validated." },
          { id: "s3", label: "Human", body: "Manager approves before status page update." },
        ],
      },
    },
    {
      id: "free",
      num: "02",
      navLabel: "Free agent",
      eyebrow: "Part 2 · Step 02",
      title: "When not to free-roam",
      lab: {
        kind: "quiz",
        prompt: "Regulated change management process. Best fit?",
        options: [
          { id: "a", label: "Deterministic workflow with LLM assist on specific steps" },
          { id: "b", label: "Fully autonomous agent picks steps" },
          { id: "c", label: "Random tool calls" },
        ],
        correctId: "a",
        ok: "Compliance loves auditable graphs — LLM fills slots, not process.",
        bad: "Free agents are hard to audit for SOX-style controls.",
      },
    },
  ],
  "incident-copilot-capstone": [
    {
      id: "story",
      num: "01",
      navLabel: "Story",
      eyebrow: "Part 1 · Step 01",
      title: "INC-1042 arc",
      prose: "Payments-api 502 during peak — engineer asks copilot for owners, runbook, and draft comms.",
      lab: {
        kind: "steps",
        steps: [
          { id: "g", label: "Graph", body: "Traverse service → owner → escalation." },
          { id: "r", label: "RAG", body: "Retrieve postmortem + rollback runbook chunks with ACL." },
          { id: "a", label: "Agent", body: "Draft Jira tasks — HITL before create." },
        ],
      },
    },
    {
      id: "check",
      num: "02",
      navLabel: "Checklist",
      eyebrow: "Part 2 · Step 02",
      title: "Ship checklist",
      lab: {
        kind: "checklist",
        intro: "Incident copilot production readiness:",
        items: [
          { id: "1", label: "Golden INC queries in CI" },
          { id: "2", label: "Cross-tenant retrieval tests" },
          { id: "3", label: "Traces with chunk ids + model route" },
          { id: "4", label: "Red team injection cases in index" },
          { id: "5", label: "Exec comms require human approve" },
        ],
        goodScore: 5,
        goodMsg: "Capstone ties graph-rag, agents, evals, and governance into one story.",
        badMsg: "Missing any row is a realistic prod incident.",
      },
    },
    {
      id: "trade",
      num: "03",
      navLabel: "Tradeoffs",
      eyebrow: "Part 2 · Step 03",
      title: "Architecture quiz",
      lab: {
        kind: "quiz",
        prompt: "Biggest risk if you ship graph+rag+agent same day without eval?",
        options: [
          { id: "a", label: "Compounding errors — wrong graph hop + confident agent action" },
          { id: "b", label: "Slower CSS" },
          { id: "c", label: "Too many citations" },
        ],
        correctId: "a",
        ok: "Layer features with eval gates — same as microservices rollout discipline.",
        bad: "Agent multiplies retrieval mistakes into external actions.",
      },
    },
  ],
};
