/**
 * Canonical list of 50 new AI workshops (not yet in repo = build from this registry).
 * Existing catalog slugs are excluded — see lib/curriculum.ts.
 */

export type RoadmapModule = {
  slug: string;
  shortTitle: string;
  title: string;
  description: string;
  wave: 1 | 2 | 3 | 4 | 5;
  trackId: "ai-basics" | "ai-core" | "ai-retrieval" | "ai-agents" | "ai-platform";
  prerequisites: string[];
  outcome: string;
  accent: string;
};

export const AI_ROADMAP_50: RoadmapModule[] = [
  {
    slug: "tokenization",
    shortTitle: "Tokenization",
    title: "Tokenization Deep Dive",
    description: "BPE intuition, token counting, and why strings split oddly for cost and context.",
    wave: 1,
    trackId: "ai-basics",
    prerequisites: ["/topics/llm-intro"],
    outcome: "Estimate token cost and explain splits on incident text.",
    accent: "#0f766e",
  },
  {
    slug: "decoding-sampling",
    shortTitle: "Decoding",
    title: "Decoding & Sampling",
    description: "Temperature, top-p, and stop sequences for support vs creative tasks.",
    wave: 1,
    trackId: "ai-basics",
    prerequisites: ["/topics/llm-intro", "/topics/tokenization"],
    outcome: "Pick decoding settings for deterministic vs varied outputs.",
    accent: "#7c3aed",
  },
  {
    slug: "neural-networks-llm",
    shortTitle: "Neural nets",
    title: "Neural Networks for LLM Users",
    description: "Layers, logits, and forward pass — enough to read architecture diagrams.",
    wave: 1,
    trackId: "ai-basics",
    prerequisites: ["/topics/llm-intro"],
    outcome: "Trace text → logits → next token without math panic.",
    accent: "#2563eb",
  },
  {
    slug: "pretraining-pipeline",
    shortTitle: "Pretraining",
    title: "The Pretraining Pipeline",
    description: "Data mix, objectives, and what pretraining actually teaches.",
    wave: 1,
    trackId: "ai-core",
    prerequisites: ["/topics/neural-networks-llm"],
    outcome: "Explain pretrain vs product behavior in plain language.",
    accent: "#9333ea",
  },
  {
    slug: "posttraining-sft",
    shortTitle: "SFT",
    title: "Post-training & SFT",
    description: "Chat templates, instruction tuning, and format compliance.",
    wave: 1,
    trackId: "ai-core",
    prerequisites: ["/topics/pretraining-pipeline"],
    outcome: "Describe what SFT changes vs what RAG must still provide.",
    accent: "#c026d3",
  },
  {
    slug: "in-context-learning",
    shortTitle: "ICL",
    title: "In-Context Learning",
    description: "Few-shot design, position effects, and distraction.",
    wave: 1,
    trackId: "ai-core",
    prerequisites: ["/topics/prompt-context"],
    outcome: "Design few-shot examples that transfer on IT tasks.",
    accent: "#db2777",
  },
  {
    slug: "hallucinations-why",
    shortTitle: "Hallucinations",
    title: "Why Models Hallucinate",
    description: "Fluent fabrication, calibration, and grounding limits.",
    wave: 1,
    trackId: "ai-core",
    prerequisites: ["/topics/rag", "/topics/llm-intro"],
    outcome: "Separate refusal, grounding, and confident wrong answers.",
    accent: "#e11d48",
  },
  {
    slug: "choosing-llm-models",
    shortTitle: "Model choice",
    title: "Choosing an LLM",
    description: "Latency, context, cost, and risk tradeoffs for internal features.",
    wave: 1,
    trackId: "ai-core",
    prerequisites: ["/topics/llm-intro"],
    outcome: "Shortlist models with a weighted decision matrix.",
    accent: "#ea580c",
  },
  {
    slug: "attention-in-depth",
    shortTitle: "Attention",
    title: "Attention in Depth",
    description: "What attends across long tickets, runbooks, and prompts.",
    wave: 1,
    trackId: "ai-core",
    prerequisites: ["/topics/transformer"],
    outcome: "Predict attention focus in a long IT thread mock.",
    accent: "#ca8a04",
  },
  {
    slug: "scaling-laws-practical",
    shortTitle: "Scaling",
    title: "Scaling Laws (Practical)",
    description: "Size vs distill vs RAG — engineering tradeoffs not papers.",
    wave: 1,
    trackId: "ai-core",
    prerequisites: ["/topics/choosing-llm-models"],
    outcome: "Argue model size vs retrieval for a copilot feature.",
    accent: "#65a30d",
  },
  {
    slug: "multimodal-fundamentals",
    shortTitle: "Multimodal",
    title: "Multimodal Fundamentals",
    description: "When images and diagrams belong in the LLM input.",
    wave: 2,
    trackId: "ai-core",
    prerequisites: ["/topics/llm-intro"],
    outcome: "Decide text-only vs vision for runbook questions.",
    accent: "#0891b2",
  },
  {
    slug: "embedding-model-choice",
    shortTitle: "Embed models",
    title: "Embedding Model Choice",
    description: "Dimensions, domains, and reindex cost.",
    wave: 2,
    trackId: "ai-core",
    prerequisites: ["/topics/embeddings"],
    outcome: "Pick embed model and dimension for an internal corpus.",
    accent: "#0d9488",
  },
  {
    slug: "loss-and-objectives",
    shortTitle: "Loss & objectives",
    title: "Loss & Training Objectives",
    description: "How objective shapes fluent but ungrounded behavior.",
    wave: 2,
    trackId: "ai-core",
    prerequisites: ["/topics/pretraining-pipeline"],
    outcome: "Map training objective to likely failure modes.",
    accent: "#4f46e5",
  },
  {
    slug: "query-rewriting",
    shortTitle: "Query rewrite",
    title: "Query Rewriting",
    description: "Rewrite, expand, and decompose for better retrieval.",
    wave: 2,
    trackId: "ai-retrieval",
    prerequisites: ["/topics/rag", "/topics/hybrid-search"],
    outcome: "Pick rewrite strategy per messy user query type.",
    accent: "#0369a1",
  },
  {
    slug: "hyde-multi-query",
    shortTitle: "HyDE",
    title: "HyDE & Multi-Query",
    description: "Hypothetical documents and multi-query fusion.",
    wave: 2,
    trackId: "ai-retrieval",
    prerequisites: ["/topics/query-rewriting"],
    outcome: "Know when HyDE helps vs adds hallucinated retrieval noise.",
    accent: "#0284c7",
  },
  {
    slug: "semantic-cache",
    shortTitle: "Semantic cache",
    title: "Semantic Caching",
    description: "Cache hits on paraphrase for latency and cost.",
    wave: 2,
    trackId: "ai-retrieval",
    prerequisites: ["/topics/embeddings"],
    outcome: "Design cache keys and thresholds for IT intents.",
    accent: "#0e7490",
  },
  {
    slug: "multi-tenant-rag",
    shortTitle: "Multi-tenant RAG",
    title: "Multi-Tenant RAG & ACLs",
    description: "Tenant and role enforcement across shared indexes.",
    wave: 2,
    trackId: "ai-retrieval",
    prerequisites: ["/topics/vector-databases", "/topics/llm-security"],
    outcome: "Prove two tenants get different grounded answers safely.",
    accent: "#155e75",
  },
  {
    slug: "rag-citations",
    shortTitle: "Citations",
    title: "Citations & Grounding UI",
    description: "Chunk pins, highlights, and trust in copilot answers.",
    wave: 2,
    trackId: "ai-retrieval",
    prerequisites: ["/topics/rag"],
    outcome: "Design citation UX that catches wrong chunk attribution.",
    accent: "#1d4ed8",
  },
  {
    slug: "conversational-rag",
    shortTitle: "Conv. RAG",
    title: "Conversational RAG",
    description: "When to re-retrieve across chat turns.",
    wave: 2,
    trackId: "ai-retrieval",
    prerequisites: ["/topics/rag", "/topics/prompt-context"],
    outcome: "Schedule retrieval refresh on follow-up questions.",
    accent: "#4338ca",
  },
  {
    slug: "structured-rag",
    shortTitle: "Structured RAG",
    title: "Structured RAG",
    description: "OpenAPI, JSON, and schema-aware chunking.",
    wave: 2,
    trackId: "ai-retrieval",
    prerequisites: ["/topics/document-parsing"],
    outcome: "Index structured internal APIs alongside prose.",
    accent: "#6d28d9",
  },
  {
    slug: "code-rag",
    shortTitle: "Code RAG",
    title: "Code RAG",
    description: "Repo chunking, symbols, and internal library search.",
    wave: 3,
    trackId: "ai-retrieval",
    prerequisites: ["/topics/chunking-strategies"],
    outcome: "Choose AST vs line chunks for internal SDK search.",
    accent: "#7e22ce",
  },
  {
    slug: "retrieval-metrics-lab",
    shortTitle: "Retrieval metrics",
    title: "Retrieval Metrics Lab",
    description: "MRR, nDCG, recall@k on golden queries.",
    wave: 3,
    trackId: "ai-retrieval",
    prerequisites: ["/topics/llm-evals", "/topics/reranking"],
    outcome: "Read metric deltas when you change rank or chunking.",
    accent: "#be185d",
  },
  {
    slug: "golden-set-design",
    shortTitle: "Golden sets",
    title: "Golden Set Design",
    description: "Coverage by intent and regression-catching sets.",
    wave: 3,
    trackId: "ai-retrieval",
    prerequisites: ["/topics/llm-evals"],
    outcome: "Draft a minimal golden set for a search feature.",
    accent: "#db2777",
  },
  {
    slug: "llm-as-judge",
    shortTitle: "LLM judge",
    title: "LLM-as-Judge",
    description: "Automated grading with bias and spot-check habits.",
    wave: 3,
    trackId: "ai-retrieval",
    prerequisites: ["/topics/llm-evals"],
    outcome: "Run judges without fooling yourself on tone bias.",
    accent: "#e11d48",
  },
  {
    slug: "synthetic-eval-data",
    shortTitle: "Synthetic evals",
    title: "Synthetic Eval Data",
    description: "Generate Q/A pairs with filters and poison checks.",
    wave: 3,
    trackId: "ai-retrieval",
    prerequisites: ["/topics/golden-set-design"],
    outcome: "When synthetic data helps vs pollutes evals.",
    accent: "#f43f5e",
  },
  {
    slug: "text-to-sql",
    shortTitle: "Text-to-SQL",
    title: "Text-to-SQL & Analytics",
    description: "Schema grounding, row limits, and deny dangerous SQL.",
    wave: 3,
    trackId: "ai-retrieval",
    prerequisites: ["/topics/tool-calling"],
    outcome: "Approve or reject generated SQL on a CMDB schema mock.",
    accent: "#c2410c",
  },
  {
    slug: "multimodal-rag",
    shortTitle: "MM RAG",
    title: "Multimodal RAG",
    description: "Diagrams and screenshots in retrieval pipelines.",
    wave: 3,
    trackId: "ai-retrieval",
    prerequisites: ["/topics/multimodal-fundamentals", "/topics/rag"],
    outcome: "Fuse image and text chunks for procedure lookup.",
    accent: "#b45309",
  },
  {
    slug: "agent-memory",
    shortTitle: "Agent memory",
    title: "Agent Memory",
    description: "Working, episodic, and semantic memory for copilots.",
    wave: 3,
    trackId: "ai-agents",
    prerequisites: ["/topics/ai-agents"],
    outcome: "Choose what to store and evict per session.",
    accent: "#059669",
  },
  {
    slug: "agent-planning",
    shortTitle: "Planning",
    title: "Agent Planning Patterns",
    description: "ReAct vs plan-and-execute vs fixed workflows.",
    wave: 3,
    trackId: "ai-agents",
    prerequisites: ["/topics/ai-agents"],
    outcome: "Match control flow to task risk and steps.",
    accent: "#0d9488",
  },
  {
    slug: "multi-agent-systems",
    shortTitle: "Multi-agent",
    title: "Multi-Agent Systems",
    description: "Routers, specialists, and handoff without loops.",
    wave: 3,
    trackId: "ai-agents",
    prerequisites: ["/topics/agent-planning"],
    outcome: "Design a router + specialist split for IT triage.",
    accent: "#0f766e",
  },
  {
    slug: "human-in-the-loop-agents",
    shortTitle: "HITL agents",
    title: "Human-in-the-Loop Agents",
    description: "Approvals before irreversible tool actions.",
    wave: 4,
    trackId: "ai-agents",
    prerequisites: ["/topics/tool-calling"],
    outcome: "Insert approval gates on ticket and prod actions.",
    accent: "#047857",
  },
  {
    slug: "durable-agent-workflows",
    shortTitle: "Durable agents",
    title: "Durable Agent Workflows",
    description: "Journals, retries, and resume after failure.",
    wave: 4,
    trackId: "ai-agents",
    prerequisites: ["/topics/ai-agents"],
    outcome: "Sketch step persistence for long-running agent jobs.",
    accent: "#065f46",
  },
  {
    slug: "agent-guardrails",
    shortTitle: "Agent guardrails",
    title: "Agent Guardrails",
    description: "Input, output, and tool policy layers.",
    wave: 4,
    trackId: "ai-agents",
    prerequisites: ["/topics/llm-evals", "/topics/llm-security"],
    outcome: "Stack policies for a tool-using copilot.",
    accent: "#166534",
  },
  {
    slug: "red-teaming",
    shortTitle: "Red teaming",
    title: "Red Teaming LLM Apps",
    description: "Attack decks and control mapping for culture + CI.",
    wave: 4,
    trackId: "ai-agents",
    prerequisites: ["/topics/llm-security"],
    outcome: "Run a lightweight red pass on a RAG feature.",
    accent: "#b91c1c",
  },
  {
    slug: "pii-dlp-ai",
    shortTitle: "PII & DLP",
    title: "PII & DLP for AI",
    description: "Detect, mask, and audit before model and logs.",
    wave: 4,
    trackId: "ai-agents",
    prerequisites: ["/topics/ai-governance"],
    outcome: "Place DLP in prompt, retrieval, and logging paths.",
    accent: "#991b1b",
  },
  {
    slug: "rag-threat-model-lab",
    shortTitle: "RAG threats",
    title: "RAG Threat Model Lab",
    description: "STRIDE on ingestion, index, retrieval, generation.",
    wave: 4,
    trackId: "ai-agents",
    prerequisites: ["/topics/llm-security", "/topics/rag"],
    outcome: "Walk threats on a data-flow diagram with controls.",
    accent: "#7f1d1d",
  },
  {
    slug: "tool-permissions-design",
    shortTitle: "Tool permissions",
    title: "Tool Permissions Design",
    description: "Scopes, allowlists, and blast radius per tool.",
    wave: 4,
    trackId: "ai-agents",
    prerequisites: ["/topics/tool-calling", "/topics/mcp-servers"],
    outcome: "Size OAuth scopes vs agent tool allowlists.",
    accent: "#dc2626",
  },
  {
    slug: "model-routing",
    shortTitle: "Routing",
    title: "Model Routing & Cascades",
    description: "Small-first routing with escalation on uncertainty.",
    wave: 4,
    trackId: "ai-platform",
    prerequisites: ["/topics/choosing-llm-models"],
    outcome: "Design a cascade with cost and latency counters.",
    accent: "#d97706",
  },
  {
    slug: "llm-cost-optimization",
    shortTitle: "Cost",
    title: "LLM Cost Optimization",
    description: "Cache, routing, context trim, and batching levers.",
    wave: 4,
    trackId: "ai-platform",
    prerequisites: ["/topics/context-windows", "/topics/semantic-cache"],
    outcome: "Prioritize cost levers for a high-QPS copilot.",
    accent: "#f59e0b",
  },
  {
    slug: "ai-slos",
    shortTitle: "AI SLOs",
    title: "SLOs for AI Features",
    description: "Latency budgets paired with quality regression alerts.",
    wave: 4,
    trackId: "ai-platform",
    prerequisites: ["/topics/ai-observability", "/topics/llm-evals"],
    outcome: "Define SLOs that include answer quality signals.",
    accent: "#eab308",
  },
  {
    slug: "quantization-inference",
    shortTitle: "Quantization",
    title: "Quantization & Inference",
    description: "INT4/8 quality tradeoffs for self-hosted models.",
    wave: 5,
    trackId: "ai-platform",
    prerequisites: ["/topics/neural-networks-llm"],
    outcome: "Explain quant tradeoffs to infra stakeholders.",
    accent: "#84cc16",
  },
  {
    slug: "local-llms",
    shortTitle: "Local LLMs",
    title: "Running LLMs Locally",
    description: "Dev laptops, Ollama, and when not to self-host.",
    wave: 5,
    trackId: "ai-platform",
    prerequisites: ["/topics/quantization-inference"],
    outcome: "Decide local vs API for dev and edge cases.",
    accent: "#65a30d",
  },
  {
    slug: "inference-serving",
    shortTitle: "Serving",
    title: "Inference Serving",
    description: "Batching, concurrency, and KV cache at the server.",
    wave: 5,
    trackId: "ai-platform",
    prerequisites: ["/topics/context-windows"],
    outcome: "Reason about queueing under concurrent chat load.",
    accent: "#4d7c0f",
  },
  {
    slug: "rlhf-alignment",
    shortTitle: "RLHF",
    title: "RLHF & Alignment (Intuition)",
    description: "Reward models and policy loops without math depth.",
    wave: 5,
    trackId: "ai-platform",
    prerequisites: ["/topics/posttraining-sft"],
    outcome: "Explain RLHF failure modes to product partners.",
    accent: "#3f6212",
  },
  {
    slug: "dpo-preferences",
    shortTitle: "DPO",
    title: "DPO & Preference Tuning",
    description: "A/B preferences as a modern alignment alternative.",
    wave: 5,
    trackId: "ai-platform",
    prerequisites: ["/topics/rlhf-alignment", "/topics/fine-tuning"],
    outcome: "Contrast DPO with RLHF for tone alignment.",
    accent: "#15803d",
  },
  {
    slug: "feature-flags-ai",
    shortTitle: "Flags",
    title: "Feature Flags for AI",
    description: "Cohort rollouts for prompts, models, and retrievers.",
    wave: 5,
    trackId: "ai-platform",
    prerequisites: ["/topics/llm-evals"],
    outcome: "Roll out model changes behind eval gates.",
    accent: "#16a34a",
  },
  {
    slug: "ai-product-metrics",
    shortTitle: "Product metrics",
    title: "AI Product Metrics",
    description: "Beyond thumbs-down: action and resolution funnels.",
    wave: 5,
    trackId: "ai-platform",
    prerequisites: ["/topics/ai-observability"],
    outcome: "Define metrics that tie answers to user outcomes.",
    accent: "#22c55e",
  },
  {
    slug: "enterprise-copilot-patterns",
    shortTitle: "Copilot patterns",
    title: "Enterprise Copilot Patterns",
    description: "Search, draft, and act patterns for IT workflows.",
    wave: 5,
    trackId: "ai-platform",
    prerequisites: ["/topics/ai-agents", "/topics/rag"],
    outcome: "Pick Q&A vs draft vs agent per workflow.",
    accent: "#10b981",
  },
  {
    slug: "workflow-automation-ai",
    shortTitle: "Workflows",
    title: "Workflow Automation with AI",
    description: "When BPMN-style beats free-form agents.",
    wave: 5,
    trackId: "ai-platform",
    prerequisites: ["/topics/agent-planning"],
    outcome: "Mix fixed steps with LLM steps safely.",
    accent: "#14b8a6",
  },
  {
    slug: "incident-copilot-capstone",
    shortTitle: "INC capstone",
    title: "Incident Copilot Capstone",
    description: "End-to-end INC → graph → RAG → agent → eval checklist.",
    wave: 5,
    trackId: "ai-platform",
    prerequisites: ["/topics/graph-rag", "/topics/llm-evals", "/topics/ai-agents"],
    outcome: "Walk a full incident copilot architecture with tradeoffs.",
    accent: "#0d9488",
  },
];

export const ROADMAP_BY_SLUG = new Map(AI_ROADMAP_50.map((m) => [m.slug, m]));
